# Generated by Django 4.0.4 on 2023-04-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_delete_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='price',
        ),
        migrations.AddField(
            model_name='article',
            name='body',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
