# Generated by Django 4.0.4 on 2023-04-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body10',
            field=models.TextField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='body2',
            field=models.TextField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='body3',
            field=models.TextField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='body4',
            field=models.TextField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='body5',
            field=models.TextField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='body6',
            field=models.TextField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='body7',
            field=models.TextField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='body8',
            field=models.TextField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='body9',
            field=models.TextField(max_length=3000, null=True),
        ),
    ]
